"""Update playbook and add executions

Revision ID: 7c750226f27e
Revises: a7ff70f832f1
Create Date: 2026-06-29 13:19:59.849653

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = '7c750226f27e'
down_revision: Union[str, None] = 'a7ff70f832f1'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('playbook_executions',
    sa.Column('playbook_name', sa.String(length=255), nullable=False),
    sa.Column('trigger', sa.String(length=255), nullable=False),
    sa.Column('status', sa.Enum('SUCCESS', 'FAILED', 'RUNNING', 'SKIPPED', name='execstatus'), nullable=False),
    sa.Column('started_at', sa.DateTime(), nullable=False),
    sa.Column('duration_s', sa.Integer(), nullable=True),
    sa.Column('steps_completed', sa.Integer(), nullable=False),
    sa.Column('steps_total', sa.Integer(), nullable=False),
    sa.Column('analyst', sa.String(length=255), nullable=False),
    sa.Column('id', sa.Uuid(), nullable=False),
    sa.Column('created_at', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=False),
    sa.Column('updated_at', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=False),
    sa.Column('is_deleted', sa.Boolean(), nullable=False),
    sa.Column('deleted_at', sa.DateTime(timezone=True), nullable=True),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index(op.f('ix_playbook_executions_is_deleted'), 'playbook_executions', ['is_deleted'], unique=False)
    op.add_column('playbooks', sa.Column('author', sa.String(length=255), server_default='System', nullable=False))
    op.add_column('playbooks', sa.Column('runs', sa.Integer(), server_default='0', nullable=False))
    op.add_column('playbooks', sa.Column('success_rate', sa.Float(), server_default='0.0', nullable=False))
    op.add_column('playbooks', sa.Column('avg_duration_s', sa.Integer(), server_default='0', nullable=False))
    op.add_column('playbooks', sa.Column('last_run', sa.DateTime(), nullable=True))
    op.add_column('playbooks', sa.Column('tags', sa.ARRAY(sa.String()), server_default='{}', nullable=False))
    op.add_column('playbooks', sa.Column('integrations', sa.ARRAY(sa.String()), server_default='{}', nullable=False))
    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_column('playbooks', 'integrations')
    op.drop_column('playbooks', 'tags')
    op.drop_column('playbooks', 'last_run')
    op.drop_column('playbooks', 'avg_duration_s')
    op.drop_column('playbooks', 'success_rate')
    op.drop_column('playbooks', 'runs')
    op.drop_column('playbooks', 'author')
    op.drop_index(op.f('ix_playbook_executions_is_deleted'), table_name='playbook_executions')
    op.drop_table('playbook_executions')
    # ### end Alembic commands ###
