"""Add knowledge module

Revision ID: a7ff70f832f1
Revises: 506435f8dfe2
Create Date: 2026-06-29 13:14:00.473432

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = 'a7ff70f832f1'
down_revision: Union[str, None] = '506435f8dfe2'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('ai_audit_logs',
    sa.Column('id', sa.UUID(), nullable=False),
    sa.Column('agent_name', sa.String(), nullable=False),
    sa.Column('target_entity_type', sa.String(), nullable=False),
    sa.Column('target_entity_id', sa.String(), nullable=False),
    sa.Column('prompt_tokens', sa.Float(), nullable=True),
    sa.Column('completion_tokens', sa.Float(), nullable=True),
    sa.Column('confidence_score', sa.Float(), nullable=True),
    sa.Column('raw_request', sa.JSON(), nullable=True),
    sa.Column('raw_response', sa.JSON(), nullable=True),
    sa.Column('reasoning', sa.Text(), nullable=True),
    sa.Column('created_at', sa.DateTime(timezone=True), nullable=True),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index(op.f('ix_ai_audit_logs_agent_name'), 'ai_audit_logs', ['agent_name'], unique=False)
    op.create_index(op.f('ix_ai_audit_logs_target_entity_id'), 'ai_audit_logs', ['target_entity_id'], unique=False)
    op.create_index(op.f('ix_ai_audit_logs_target_entity_type'), 'ai_audit_logs', ['target_entity_type'], unique=False)
    op.create_table('knowledge_articles',
    sa.Column('title', sa.String(length=255), nullable=False),
    sa.Column('category', sa.Enum('SOP', 'IR', 'Intel', 'Admin', 'General', name='doccategory'), nullable=False),
    sa.Column('description', sa.Text(), nullable=False),
    sa.Column('content', sa.Text(), nullable=False),
    sa.Column('checklist', sa.ARRAY(sa.String()), nullable=False),
    sa.Column('commands', sa.ARRAY(sa.String()), nullable=True),
    sa.Column('contacts', sa.ARRAY(sa.String()), nullable=True),
    sa.Column('tags', sa.ARRAY(sa.String()), nullable=False),
    sa.Column('id', sa.Uuid(), nullable=False),
    sa.Column('created_at', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=False),
    sa.Column('updated_at', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=False),
    sa.Column('is_deleted', sa.Boolean(), nullable=False),
    sa.Column('deleted_at', sa.DateTime(timezone=True), nullable=True),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index(op.f('ix_knowledge_articles_is_deleted'), 'knowledge_articles', ['is_deleted'], unique=False)
    op.create_index(op.f('ix_knowledge_articles_title'), 'knowledge_articles', ['title'], unique=False)
    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_index(op.f('ix_knowledge_articles_title'), table_name='knowledge_articles')
    op.drop_index(op.f('ix_knowledge_articles_is_deleted'), table_name='knowledge_articles')
    op.drop_table('knowledge_articles')
    op.drop_index(op.f('ix_ai_audit_logs_target_entity_type'), table_name='ai_audit_logs')
    op.drop_index(op.f('ix_ai_audit_logs_target_entity_id'), table_name='ai_audit_logs')
    op.drop_index(op.f('ix_ai_audit_logs_agent_name'), table_name='ai_audit_logs')
    op.drop_table('ai_audit_logs')
    # ### end Alembic commands ###
